version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      - DATABASE_URL=${{ mysite-6yvA.DATABASE_URL }}
      - RAILS_MASTER_KEY=b2c98438f933b7eee93e93f01b18d4f3
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_shopping_system
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
