# # version: '2.2'
# services:
#   db:
#     image: postgres:14.2-alpine
#     container_name: db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     command:
#       "postgres -c 'max_connections=500'"
#     environment:
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"

#   commerce-web:
#     build: "./bin/rails server"
#     environment:
#       - RAILS_ENV=${RAILS_ENV}
#       - POSTGRES_HOST=${POSTGRES_HOST}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     volumes:
#       - app-storage:/rails/storage
#     depends-on:
#       - db

# volumes:
#   postgres_data: {}
#   app-storage: {}

version: '2.2'

services:
  db:
    image: postgres:14.2-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  commerce-web:
    build:
      context: ./bin     # Specify the build context directory for your Rails app
      dockerfile: ../Dockerfile
    command: ["rails", "server"]
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  app-storage:
