
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  port: 5432
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: online_shopping_system
  host: db
  username: postgres
  password: password
  port: 5432

# development:
#   <<: *default
#   database: online_shopping_system_development
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   host: <%= ENV['POSTGRES_HOST'] %>
#   port: 5432

test:
  <<: *default
  database: online_shopping_system_test
  host: db
  username: postgres
  password: password
  port: 5432

production:
  <<: *default
  database: online_shopping_system_production
  host: db
  username: postgres
  password: password
  port: 5432
